sudo: false
language: scala
scala:
    - 2.11.7

notifications:
  email: false

branches:
    only:
        - master

script:
  - gradle test
  - gradle testScoverage

after_success:
  - pip install --user codecov && codecov
