sudo: false
language: scala
scala:
    - 2.11.7

notifications:
  email: false

branches:
    only:
        - master

script:
  - sbt ++$TRAVIS_SCALA_VERSION test:compile
  - CP=$(sbt "export test:dependency-classpath" --error)
  - java -cp $CP org.scalatest.tools.Runner -R target/scala-2.11/test-classes -o -PS3
